#!/bin/bash
cp Steady/restart_flow.dat restart_flow_00001.dat
cp Steady/restart_flow.dat restart_flow_00002.dat
mpirun -np 10 --use-hwthread-cpus python3 -m mpi4py sinmotion.py -f inc_ground.cfg --parallel 
